version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: it-nk-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespass}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/data/postgres
    networks:
      - it-nk-service-postgres
    restart: unless-stopped
    env_file:
      - .env

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env

  # backend:
  #   build: .
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   ports:
  #     -"8000:8000"
  #   depends_on:
  #     - postgres

networks:
  it-nk-service-postgres:
    driver: bridge

volumes:
  postgres_data:
  telegram-bot-api-data: